const fs = require('fs');
let txt = fs.readFileSync('src/pages/CandidateForm.jsx', 'utf8');

const replacements = [
  ['Tuy\uFFFD!t vời', 'Tuyệt vời'],
  ['H\uFFFD  sơ', 'Hồ sơ'],
  ['\uFFFD ã', 'đã'],
  ['\uFFFD Ồ', 'để'],
  ['n\uFFFD"p', 'nộp'],
  ['N\uFFFD"p', 'Nộp'],
  ['\uFFFD iền', 'điền'],
  ['vĒn', 'văn'],
  ['ch\uFFFD0', 'chỉ'],
  ['\uFFFD ạt', 'đạt'],
  ['T\uFFFD" trư\uFFFDxng', 'Tổ trưởng'],
  ['T\uFFFD"', 'Tổ'],
  ['trư\uFFFDxng', 'trưởng'],
  ['S\uFFFD  quyết', 'Số quyết'],
  ['S\uFFFD  Quyết', 'Số Quyết'],
  ['quyết \uFFFD \uFFFD9nh', 'quyết định'],
  ['Quyết \uFFFD \uFFFD9nh', 'Quyết định'],
  ['\uFFFD \uFFFD9nh', 'định'],
  ['Chuy\uFFFDỒn', 'Chuyển'],
  ['báo l\uFFFD i', 'báo lỗi'],
  ['Tập th\uFFFDỒ', 'Tập thể'],
  ['l\uFFFD i', 'lỗi'],
  ['Kh\uFFFDng', 'Không'],
  ['m\uFFFDục', 'mục'],
  ['ch\uFFFD0nh', 'chỉnh'],
  ['b\uFFFD9', 'bị'],
  ['tr\uFFFDả', 'trả'],
  ['l\uFFFDại', 'lại'],
  ['ki\uFFFDỒm', 'kiểm'],
  ['th\uFFFD’', 'thể'],
  ['b\uFFFD"', 'bộ'],
  ['t\uFFFD0nh', 'tỉnh'],
  ['tư\uFFFD:ng', 'tướng'],
  ['v\uFFFD9', 'vị'],
  ['th\uFFFD"c', 'thuộc'],
  ['quy \uFFFD \uFFFD9nh', 'quy định'],
  ['\uFFFD i\uFFFD’m', 'điểm'],
  ['\uFFFD \uFFFD"ng', 'động'],
  ['di\uFFFD!n', 'diện'],
  ['hi\uFFFD!u', 'hiệu'],
  ['thi\uFFFD!n', 'thiện'],
  ['\uFFFD \uFFFD"', 'Độ'],
  ['\uFFFD a', 'Đa'],
  ['\uFFFD ính', 'đính'],
  ['cst\uFFFD ', 'cstđ'],
  [' \uFFFD ua', ' đua'],
  ['l\uFFFD:n', 'lớn'],
  ['dư\uFFFD:i', 'dưới'],
  ['mu\uFFFD n', 'muốn'],
  ['bu\uFFFD"c', 'buộc'],
  ['\uFFFD ánh', 'đánh'],
  ['\uFFFD ược', 'được'],
  ['\uFFFDx ', 'ở '],
  ['nghi\uFFFD!p', 'nghiệp'],
  ['\uFFFD ủ', 'đủ'],
  ['\uFFFD iều', 'điều'],
  ['ki\uFFFD!n', 'kiện'],
  ['\uFFFD ầy', 'đầy'],
  ['m\uFFFD"i', 'mũi'],
  ['l\uFFFD!', 'lệ'],
  ['\uFFFD', 'đ'], // fallback for standalone \uFFFD
];

for (let [bad, good] of replacements) {
  txt = txt.split(bad).join(good);
}

fs.writeFileSync('src/pages/CandidateForm.jsx', txt, 'utf8');
console.log('Fixed CandidateForm.jsx');